CREATE TABLE "deback-doko_game_result" (
	"id" text PRIMARY KEY NOT NULL,
	"table_id" text NOT NULL,
	"created_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "deback-doko_player_game_result" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deback-doko_player_game_result_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"game_result_id" text NOT NULL,
	"user_id" text NOT NULL,
	"score" integer NOT NULL,
	"team" text NOT NULL,
	"won" boolean NOT NULL,
	"balance_change" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "deback-doko_user" ADD COLUMN "games_played" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "deback-doko_user" ADD COLUMN "games_won" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "deback-doko_player_game_result" ADD CONSTRAINT "deback-doko_player_game_result_game_result_id_deback-doko_game_result_id_fk" FOREIGN KEY ("game_result_id") REFERENCES "public"."deback-doko_game_result"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deback-doko_player_game_result" ADD CONSTRAINT "deback-doko_player_game_result_user_id_deback-doko_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."deback-doko_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "player_game_result_user_idx" ON "deback-doko_player_game_result" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "player_game_result_game_idx" ON "deback-doko_player_game_result" USING btree ("game_result_id");