import "@/styles/globals.css";
// biome-ignore lint/correctness/noUnusedImports: for vercel analytics
import { Analytics } from "@vercel/analytics/next";
import type { Metadata } from "next";
import { IBM_Plex_Mono, Libre_Baskerville, Poppins } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

const poppins = Poppins({
	subsets: ["latin"],
	variable: "--font-poppins",
	weight: ["400", "500", "600", "700"],
});

const libreBaskerville = Libre_Baskerville({
	subsets: ["latin"],
	variable: "--font-libre-baskerville",
	weight: ["400", "700"],
});

const ibmPlexMono = IBM_Plex_Mono({
	subsets: ["latin"],
	variable: "--font-ibm-plex-mono",
	weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Doppelkopf Online",
	description: "Generated by Deback Development",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html
			className={cn(
				"bg-background text-foreground antialiased",
				poppins.variable,
				libreBaskerville.variable,
				ibmPlexMono.variable,
			)}
			lang="de"
			suppressHydrationWarning
		>
			<body className="min-h-screen bg-wood-pattern">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					disableTransitionOnChange
					enableSystem
				>
					<TooltipProvider>
						{children}
						<Toaster position="top-center" />
					</TooltipProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
