import "@/styles/globals.css";
// biome-ignore lint/correctness/noUnusedImports: for vercel analytics
import { Analytics } from "@vercel/analytics/next";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
	title: "Doppelkopf Online",
	description: "Generated by Deback Development",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html
			className={cn(
				"bg-background text-foreground antialiased",
				geist.variable,
			)}
			lang="en"
			suppressHydrationWarning
		>
			<body className="min-h-screen bg-wood">{children}</body>
		</html>
	);
}
